import React, { useState } from 'react';
import toast from 'react-hot-toast';
import { Copy, Download, Check, Code2, Server, Shield, Cloud } from 'lucide-react';
import { Modal } from '../common/Modal';
import type { Recommendation } from '../../types';

interface GatewayExporterModalProps {
  isOpen: boolean;
  onClose: () => void;
  recommendation: Recommendation | null;
}

type GatewayFormat = 'nginx' | 'kong' | 'cloudflare' | 'envoy';

export const GatewayExporterModal: React.FC<GatewayExporterModalProps> = ({
  isOpen,
  onClose,
  recommendation,
}) => {
  const [activeFormat, setActiveFormat] = useState<GatewayFormat>('nginx');
  const [copied, setCopied] = useState(false);

  if (!recommendation) return null;

  const rps = recommendation.recommendedRateLimitRps || 300;
  const targetUrl = recommendation.targetUrl || 'http://localhost:8080/api/products';
  const urlPath = (() => {
    try {
      return new URL(targetUrl).pathname;
    } catch {
      return '/api/products';
    }
  })();

  const generateConfig = (format: GatewayFormat): { code: string; filename: string; lang: string } => {
    switch (format) {
      case 'nginx':
        return {
          filename: `ratescale-nginx-${urlPath.replace(/\//g, '_')}.conf`,
          lang: 'nginx',
          code: `# Nginx Rate Limiting Config generated by RateScale AI
# Recommended Limit: ${rps} RPS | Model: ${recommendation.modelVersion}
# Target Endpoint: ${targetUrl}

http {
    # Define rate limiting zone based on client IP
    limit_req_zone $binary_remote_addr zone=ratescale_zone:10m rate=${rps}r/s;
    limit_req_status 429;

    server {
        listen 80;
        server_name api.yourdomain.com;

        location ${urlPath} {
            # Apply rate limiting with burst allowance of ${Math.floor(rps * 0.2)}
            limit_req zone=ratescale_zone burst=${Math.floor(rps * 0.2)} nodelay;

            proxy_pass ${targetUrl};
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}`,
        };

      case 'kong':
        return {
          filename: `ratescale-kong-${urlPath.replace(/\//g, '_')}.yml`,
          lang: 'yaml',
          code: `# Kong Declarative Rate Limiting Plugin generated by RateScale AI
# Recommended Limit: ${rps} RPS | Model: ${recommendation.modelVersion}

_format_version: "3.0"
services:
  - name: ratescale-service-${urlPath.replace(/\//g, '-')}
    url: ${targetUrl}
    routes:
      - name: ratescale-route
        paths:
          - ${urlPath}
    plugins:
      - name: rate-limiting
        config:
          second: ${rps}
          minute: ${rps * 60}
          policy: local
          fault_tolerant: true
          hide_client_headers: false
          error_code: 429
          error_message: "Rate limit exceeded. Allowed: ${rps} req/sec."`,
        };

      case 'cloudflare':
        return {
          filename: `ratescale-cloudflare-${urlPath.replace(/\//g, '_')}.json`,
          lang: 'json',
          code: JSON.stringify(
            {
              description: `RateScale AI Protection Rule for ${urlPath}`,
              action: "simulate",
              ratelimit: {
                characteristics: ["ip.src"],
                period: 1,
                requests_per_period: rps,
                mitigation_timeout: 60,
              },
              match: {
                request: {
                  url: `*yourdomain.com${urlPath}*`,
                  methods: ["GET", "POST", "PUT", "DELETE"],
                },
              },
              response: {
                status: 429,
                content_type: "application/json",
                body: JSON.stringify({
                  error: "Too Many Requests",
                  message: `Rate limit threshold of ${rps} RPS exceeded.`,
                }),
              },
            },
            null,
            2
          ),
        };

      case 'envoy':
        return {
          filename: `ratescale-envoy-${urlPath.replace(/\//g, '_')}.yaml`,
          lang: 'yaml',
          code: `# Envoy Proxy Rate Limit Filter generated by RateScale AI
# Recommended Limit: ${rps} RPS | Model: ${recommendation.modelVersion}

domain: ratescale_protected_gateway
descriptors:
  - key: request_headers
    value: path
    descriptors:
      - key: remote_address
        rate_limit:
          unit: SECOND
          requests_per_unit: ${rps}

# Envoy HTTP Connection Manager Filter Configuration:
# - name: envoy.filters.http.ratelimit
#   typed_config:
#     "@type": type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
#     domain: ratescale_protected_gateway
#     rate_limit_service:
#       grpc_service:
#         envoy_grpc:
#           cluster_name: ratescale_ratelimit_service`,
        };
    }
  };

  const currentConfig = generateConfig(activeFormat);

  const handleCopy = () => {
    navigator.clipboard.writeText(currentConfig.code);
    setCopied(true);
    toast.success(`Copied ${activeFormat.toUpperCase()} configuration to clipboard!`);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([currentConfig.code], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = currentConfig.filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    toast.success(`Downloaded ${currentConfig.filename}`);
  };

  const tabs = [
    { id: 'nginx' as const, label: 'Nginx', icon: Server },
    { id: 'kong' as const, label: 'Kong API Gateway', icon: Shield },
    { id: 'cloudflare' as const, label: 'Cloudflare Rules', icon: Cloud },
    { id: 'envoy' as const, label: 'Envoy / AWS', icon: Code2 },
  ];

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title="Export API Gateway Configuration"
      subtitle={`Export AI Recommended Policy (${rps} RPS) to Production Gateway Configs`}
      maxWidth="xl"
    >
      <div className="space-y-4">
        {/* Gateway Format Selector Tabs */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 p-1 bg-zinc-900 border border-zinc-800 rounded-xl">
          {tabs.map((tab) => {
            const Icon = tab.icon;
            const isActive = activeFormat === tab.id;
            return (
              <button
                key={tab.id}
                type="button"
                onClick={() => setActiveFormat(tab.id)}
                className={`flex items-center justify-center gap-2 py-2 px-3 rounded-lg text-xs font-semibold transition-all ${
                  isActive
                    ? 'bg-zinc-100 text-zinc-950 shadow-xs'
                    : 'text-zinc-400 hover:text-zinc-100 hover:bg-zinc-800/60'
                }`}
              >
                <Icon className={`w-3.5 h-3.5 ${isActive ? 'text-blue-600' : 'text-zinc-500'}`} />
                <span>{tab.label}</span>
              </button>
            );
          })}
        </div>

        {/* Code Preview Header */}
        <div className="flex items-center justify-between px-1">
          <span className="text-xs font-mono text-zinc-400">
            {currentConfig.filename}
          </span>
          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={handleCopy}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium bg-zinc-900 border border-zinc-800 text-zinc-200 hover:bg-zinc-800 transition-colors"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied!' : 'Copy Code'}</span>
            </button>

            <button
              type="button"
              onClick={handleDownload}
              className="inline-flex items-center gap-1.5 px-3.5 py-1.5 rounded-lg text-xs font-semibold bg-zinc-100 text-zinc-950 hover:bg-white transition-colors shadow-xs"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download File</span>
            </button>
          </div>
        </div>

        {/* Code Block Container */}
        <div className="relative rounded-xl border border-zinc-800 bg-zinc-950 p-4 font-mono text-xs text-emerald-400 overflow-x-auto max-h-80 select-all leading-relaxed shadow-inner">
          <pre>{currentConfig.code}</pre>
        </div>

        {/* Footer Note */}
        <div className="p-3 rounded-lg bg-zinc-900/60 border border-zinc-800/80 text-[11px] text-zinc-400 flex items-center justify-between">
          <span>
            Target: <strong className="text-zinc-200 font-mono">{targetUrl}</strong>
          </span>
          <span className="text-blue-400 font-semibold">Quota: {rps} req/sec</span>
        </div>
      </div>
    </Modal>
  );
};
